{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "template-operator-v2.fullname" . }}-selfsigned-issuer
  labels:
  {{- include "template-operator-v2.labels" . | nindent 4 }}
spec:
  selfSigned: {}
{{- end }}
