resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:657f0e273f646c87aad81d9468c5b2fb593aab00397a4c9350568525652b52da
  name: controller
  newName: registry.connect.redhat.com/stakater/mto-dependencies-operator
