resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:aacb6bda77f58aa2df835e337a86a5a3461b4c633dd148c262b1faecb18002fb
  name: controller
  newName: registry.connect.redhat.com/stakater/mto-dependencies-operator
