apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: finops-operator-finopsprovider-viewer-role
  labels:
  {{- include "finops-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - finops.stakater.com
  resources:
  - finopsproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - finops.stakater.com
  resources:
  - finopsproviders/status
  verbs:
  - get
