{{- if .Values.mdoDependencies.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.prometheus }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  PROMETHEUS_URL: "http://{{ .Release.Name }}-prometheus-server.{{ .Release.Namespace }}.svc.cluster.local"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_CONNECTION_STRING: "postgresql://{{ .Values.mdoDependencies.postgres.username }}:{{ .Values.mdoDependencies.postgres.password }}@{{ .Release.Name }}-postgres-postgresql.{{ .Release.Namespace }}.svc.cluster.local:5432/{{ .Values.mdoDependencies.postgres.database }}?sslmode=disable"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.opencost }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  OPENCOST_CONNECTION_STRING: "http://{{ .Release.Name }}-opencost.{{ .Release.Namespace }}.svc.cluster.local:9003"
{{- end }}
