apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: finops-operator-pricebook-editor-role
  labels:
  {{- include "finops-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - finops.stakater.com
  resources:
  - pricebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.stakater.com
  resources:
  - pricebooks/status
  verbs:
  - get
