{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "finops-operator.fullname" . }}-serving-cert
  labels:
  {{- include "finops-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - 'finops-operator-webhook-service.{{ .Release.Namespace
    }}.svc'
  - 'finops-operator-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: {{ include "finops-operator.fullname" . }}-selfsigned-issuer
  secretName: webhook-server-cert
{{- end }}
