#!/usr/bin/env bash
#
# Generate the CRD-adoption hook job for every chart that ships CRDs.
#
# These charts keep their CRDs in templates/ rather than crds/, because Helm
# applies crds/ only on install and helm-operator upgrades the release on every
# reconcile. Helm refuses to apply a resource it does not own, so a CRD created
# before that move -- by the chart's old crds/ directory, or by any other
# installer -- makes every later upgrade fail with "invalid ownership metadata".
#
# The generated job runs as a pre-install/pre-upgrade hook and stamps the Helm
# ownership label and annotations onto those CRDs, so Helm adopts them instead
# of refusing them. Charts that ship no CRDs get no job.
#
# Usage: gen-crd-adoption-jobs.sh [--check] <charts-dir> <image> [yq-binary]
#
#   --check  report what would change and exit non-zero instead of writing.

set -euo pipefail

JOB_FILE=crd-adoption-job.yaml

check=false
if [ "${1:-}" = "--check" ]; then
    check=true
    shift
fi

charts_dir=${1:?charts directory required}
image=${2:?default job image required}
yq=${3:-yq}

# crd_names <chart-dir> -- names of the CRDs the chart ships, one per line.
crd_names() {
    local f
    for f in "$1"/templates/*.yaml; do
        [ -e "$f" ] || continue
        grep -q '^kind: CustomResourceDefinition$' "$f" || continue
        "$yq" e '.metadata.name' "$f"
    done | sort -u
}

# render <crd-name>... -- the job manifest, on stdout.
render() {
    cat <<'HEADER'
{{- /*
Generated by 'make gen-crd-adoption-jobs'. Do not edit by hand.

This chart ships its CRDs in templates/ so that every helm upgrade applies them.
Helm refuses to apply a resource it does not own, so CRDs created before that
move fail every upgrade with "invalid ownership metadata". This hook stamps the
Helm ownership label and annotations onto them first, so Helm adopts them.

Set crdAdoption.enabled to false to skip it.
*/ -}}
{{- $adoption := .Values.crdAdoption | default dict -}}
{{- if ne (toString $adoption.enabled) "false" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-crd-adoption
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-crd-adoption
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-crd-adoption
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-crd-adoption
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-crd-adoption
    namespace: {{ .Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-crd-adoption
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 120
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: {{ .Release.Name }}-crd-adoption
      securityContext:
        runAsNonRoot: true
      containers:
        - name: adopt
          image: {{ $adoption.image | default "IMAGE_PLACEHOLDER" | quote }}
          imagePullPolicy: {{ $adoption.imagePullPolicy | default "IfNotPresent" }}
          env:
            - name: RELEASE_NAME
              value: {{ .Release.Name | quote }}
            - name: RELEASE_NAMESPACE
              value: {{ .Release.Namespace | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 64Mi
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -eu
              sa=/var/run/secrets/kubernetes.io/serviceaccount
              api=https://kubernetes.default.svc/apis/apiextensions.k8s.io/v1/customresourcedefinitions
              patch=$(printf \
                '{"metadata":{"labels":{"app.kubernetes.io/managed-by":"Helm"},"annotations":{"meta.helm.sh/release-name":"%s","meta.helm.sh/release-namespace":"%s"}}}' \
                "$RELEASE_NAME" "$RELEASE_NAMESPACE")
              for crd in \
HEADER

    local name last
    last=$#
    local i=0
    for name in "$@"; do
        i=$((i + 1))
        if [ "$i" -eq "$last" ]; then
            printf '                %s\n' "$name"
        else
            printf '                %s \\\n' "$name"
        fi
    done

    cat <<'FOOTER'
              do
                code=$(curl -sS -o /tmp/response -w '%{http_code}' \
                  --cacert "$sa/ca.crt" \
                  -H "Authorization: Bearer $(cat "$sa/token")" \
                  -H 'Content-Type: application/merge-patch+json' \
                  -X PATCH "$api/$crd" --data "$patch")
                case "$code" in
                  200) echo "adopted $crd" ;;
                  404) echo "skipped $crd (not installed yet)" ;;
                  *) echo "failed to adopt $crd (HTTP $code)"; cat /tmp/response; exit 1 ;;
                esac
              done
{{- end }}
FOOTER
}

stale=0

for chart in "$charts_dir"/*/; do
    chart_name=$(basename "$chart")
    job_path="$chart/templates/$JOB_FILE"

    # shellcheck disable=SC2207
    names=($(crd_names "$chart"))

    if [ ${#names[@]} -eq 0 ]; then
        if [ -e "$job_path" ]; then
            if $check; then
                echo "  $chart_name: ships no CRDs but still has templates/$JOB_FILE"
                stale=1
            else
                rm -f "$job_path"
                echo "✓ $chart_name: removed templates/$JOB_FILE (chart ships no CRDs)"
            fi
        fi
        continue
    fi

    rendered=$(render "${names[@]}" | sed "s|IMAGE_PLACEHOLDER|$image|")

    if $check; then
        if [ ! -e "$job_path" ]; then
            echo "  $chart_name: missing templates/$JOB_FILE"
            stale=1
        elif ! diff -u "$job_path" <(printf '%s\n' "$rendered") > /dev/null; then
            echo "  $chart_name: templates/$JOB_FILE is out of date"
            stale=1
        fi
        if [ "$("$yq" e '.crdAdoption.image // "null"' "$chart/values.yaml")" = "null" ]; then
            echo "  $chart_name: values.yaml has no crdAdoption.image"
            stale=1
        fi
        continue
    fi

    printf '%s\n' "$rendered" > "$job_path"
    "$yq" -i ".crdAdoption.image = \"$image\"" "$chart/values.yaml"
    echo "✓ $chart_name: generated templates/$JOB_FILE for ${#names[@]} CRD(s)"
done

if $check && [ "$stale" -ne 0 ]; then
    echo "Run 'make gen-crd-adoption-jobs' and commit the result."
    exit 1
fi
