apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dex-config-operator.fullname" . }}-localuser-admin-role
  labels:
  {{- include "dex-config-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - auth.stakater.com
  resources:
  - localusers
  verbs:
  - '*'
- apiGroups:
  - auth.stakater.com
  resources:
  - localusers/status
  verbs:
  - get
